# Lista de versões do xk6:
# https://github.com/grafana/xk6/releases

# Extensão para SQL Server:
# https://github.com/grafana/xk6-sql

trigger:
- main

variables:
  loadTestsScript: 'loadtests-produtos-sqlserver.js'
  htmtReportK6: 'sqlserver-loadtests.html'
  testsDirectory: './Tests'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Tests
  displayName: Tests stage
  jobs:
  - job: Tests
    displayName: Tests
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: replacetokens@5
      inputs:
        targetFiles: '$(testsDirectory)/$(loadTestsScript)'
        encoding: 'auto'
        tokenPattern: 'default'
        writeBOM: true
        actionOnMissing: 'warn'
        keepToken: false
        actionOnNoFiles: 'continue'
        enableTransforms: false
        enableRecursion: false
        useLegacyPattern: false
        defaultValue: '$(TesteConexao)'
        enableTelemetry: true
      displayName: Configurar a string de conexão do SQL Server no script de testes
    - script: |
        cd $(testsDirectory)
        wget https://github.com/grafana/xk6/releases/download/v0.6.1/xk6_0.6.1_linux_amd64.tar.gz
        tar -xvf xk6_0.6.1_linux_amd64.tar.gz
      displayName: Baixar e instalar o módulo do k6 para extensões (xk6)
    - script: |
        cd $(testsDirectory)
        ./xk6 build master --with github.com/grafana/xk6-sql
        ./k6
      displayName: Gerar o executável do k6 com suporte ao SQL Server
    - script: |
        cd $(testsDirectory)
        ./k6 run $(loadTestsScript)
        echo '...'
        ls
      displayName: Executar testes de carga acessando o SQL Server
    - task: PublishHtmlReport@1
      condition: always()
      inputs:
        reportDir: $(testsDirectory)/$(htmtReportK6)
      displayName: Publicar relatório com os resultados dos testes